// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMu_QM3TxK2_kMcSFN_c4Gy1K3bFHA4Y',
    appId: '1:894392029195:web:eda6f1c759d470f21ff70e',
    messagingSenderId: '894392029195',
    projectId: 'awareplus-6645f',
    authDomain: 'awareplus-6645f.firebaseapp.com',
    storageBucket: 'awareplus-6645f.firebasestorage.app',
    measurementId: 'G-E7005ZCB3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2YSLjCWOk1cs93NiuykgLAadaiA87ek',
    appId: '1:894392029195:android:d46e44c0928826e91ff70e',
    messagingSenderId: '894392029195',
    projectId: 'awareplus-6645f',
    storageBucket: 'awareplus-6645f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQG7PlY1klZOyd6iwHWBzpFQJqPVw138',
    appId: '1:894392029195:ios:0c845e79848b6be91ff70e',
    messagingSenderId: '894392029195',
    projectId: 'awareplus-6645f',
    storageBucket: 'awareplus-6645f.firebasestorage.app',
    iosBundleId: 'com.example.awarePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQG7PlY1klZOyd6iwHWBzpFQJqPVw138',
    appId: '1:894392029195:ios:0c845e79848b6be91ff70e',
    messagingSenderId: '894392029195',
    projectId: 'awareplus-6645f',
    storageBucket: 'awareplus-6645f.firebasestorage.app',
    iosBundleId: 'com.example.awarePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMu_QM3TxK2_kMcSFN_c4Gy1K3bFHA4Y',
    appId: '1:894392029195:web:21552e6ea6fceb561ff70e',
    messagingSenderId: '894392029195',
    projectId: 'awareplus-6645f',
    authDomain: 'awareplus-6645f.firebaseapp.com',
    storageBucket: 'awareplus-6645f.firebasestorage.app',
    measurementId: 'G-CFD74MM2B8',
  );
}
